### ISSUE TITLE
Configurable URL & suffix

### ISSUE THREAD

**Issue by realSaltyFish** [BoYanZh/focs-gitea#1]
https://github.com/BoYanZh/Joint-Teapot/pull/10

To align with the Mattermost module and increase generality, it's a good idea to let the user specify a gitea URL and a suffix (`/git` for FOCS) rather than hard-coding these.

**Comment by BoYanZh** [comment]
https://github.com/BoYanZh/focs-gitea/blob/cb8e070e3ee16d21f82dd01d79f6fc982c758da4/focs_gitea/configuration.py#L43
